### ISSUE TITLE
首次选中失效

### ISSUE THREAD

**Issue by Jacky-LinPeng** [zeqinjie/ZQEndlessPageControl#1]
项目里面设置了
[UICollectionView appearance].semanticContentAttribute = UISemanticContentAttributeForceLeftToRight;

然后执行pagecontrol的视图setup 选中会无效

**Comment by zeqinjie** [comment]
@Jacky-LinPeng v0.3.2 已处理，感谢反馈

**Comment by Jacky-LinPeng** [comment]
`collectionView.semanticContentAttribute = .unspecified`
我之前也试过你这个设置，但是这个改动之后 这个控件就不支持RTL了呀，心里就有点疙瘩
我还尝试了这样的方式也是可行的（DispatchQueue.main.async），但是不明白本质问题出在哪。。。为啥会这样？好难受 哈,,,
`
 public func setup(configuration: GLPageControlConfiguration) {
        self.configuration = configuration
        setupConstraints()
        DispatchQueue.main.async {
            self.setupInitialSelection()
            self.updateCells()
        }
    }
`

**Comment by Jacky-LinPeng** [comment]
collectionView.semanticContentAttribute = .unspecified
我之前也试过你这个设置，但是这个改动之后 这个控件就不支持RTL了呀，心里就有点疙瘩
我还尝试了这样的方式也是可行的（setup方法包裹一个 DispatchQueue.main.async），但是不明白本质问题出在哪。。。为啥会这样？好难受 哈,,,
